In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv('sh.600000.csv')

In [3]:
print(data.head(5))
print(data.tail(5))

         date       code       open       high        low      close  \
0  2017-12-07  sh.600000  12.814685  12.893850  12.775103  12.824581
1  2017-12-08  sh.600000  12.844372  12.854267  12.735521  12.794894
2  2017-12-11  sh.600000  12.784999  12.903745  12.715730  12.834476
3  2017-12-12  sh.600000  12.834476  12.834476  12.606880  12.616775
4  2017-12-13  sh.600000  12.666253  12.676148  12.498029  12.606880

    preclose    volume       amount  adjustflag      turn  tradestatus  \
0  12.824581  34802229  451233524.0           2  0.123835            1
1  12.824581  31296221  404411517.0           2  0.111360            1
2  12.794894  36649902  474566888.0           2  0.130409            1
3  12.834476  30370097  390113096.0           2  0.108064            1
4  12.616775  19345338  246331123.0           2  0.068835            1

     pctChg     peTTM     pbMRQ     psTTM  pcfNcfTTM  isST
0  0.000000  7.004418  0.981842  2.310626  -2.043354     0
1 -0.231479  6.988205  0.979569  2.305277  -2.038624     0
2  0.309358  7.009823  0.982600  2.312409  -2.044930     0
3 -1.696224  6.890921  0.965933  2.273185  -2.010244     0
4 -0.078433  6.885516  0.965175  2.271402  -2.008667     0
           date       code   open   high    low  close  preclose    volume  \
240  2018-12-03  sh.600000  10.99  11.05  10.84  11.02     10.71  43049070
241  2018-12-04  sh.600000  11.00  11.08  10.97  11.08     11.02  20811293
242  2018-12-05  sh.600000  10.99  11.10  10.96  11.00     11.08  25491217
243  2018-12-06  sh.600000  10.82  10.93  10.82  10.90     11.00  23597997
244  2018-12-07  sh.600000  10.94  11.03  10.88  10.89     10.90  10580550

          amount  adjustflag      turn  tradestatus    pctChg     peTTM  \
240  472438382.0           2  0.153179            1  2.894495  5.820451
241  229713745.0           2  0.074052            1  0.544460  5.852141
242  281189602.0           2  0.090704            1 -0.722021  5.809888
243  256533148.0           2  0.083967            1 -0.909094  5.757070
244  115760323.0           2  0.037648            1 -0.091736  5.751789

        pbMRQ     psTTM  pcfNcfTTM  isST
240  0.760281  1.899833   3.113035     0
241  0.764420  1.910177   3.129985     0
242  0.758901  1.896385   3.107385     0
243  0.752002  1.879146   3.079136     0
244  0.751312  1.877422   3.076312     0

In [6]:
data.describe()

,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM,isST
count,245.000000,245.000000,245.000000,245.000000,245.000000,2.450000e+02,2.450000e+02,245.0,245.000000,245.0,245.000000,245.000000,245.000000,245.000000,245.000000,245.0
mean,11.095712,11.189029,10.992367,11.084785,11.092682,3.582759e+07,4.270868e+08,2.0,0.127483,1.0,-0.083437,6.019194,0.822677,1.960009,8.323278,0.0
std,1.132764,1.144871,1.125110,1.136245,1.141595,4.524912e+07,6.108954e+08,0.0,0.161007,0.0,1.392350,0.643421,0.104405,0.200529,10.900488,0.0
min,9.163242,9.252302,9.074183,9.163242,9.163242,8.995716e+06,9.169444e+07,2.0,0.032009,1.0,-5.391040,5.023942,0.682401,1.644255,-2.152143,0.0
25%,10.170000,10.270000,10.100000,10.170000,10.170000,1.755753e+07,1.882069e+08,2.0,0.062474,1.0,-0.771871,5.495953,0.735460,1.798737,-1.958214,0.0
50%,10.815792,10.885061,10.700000,10.786106,10.786106,2.294848e+07,2.417497e+08,2.0,0.081656,1.0,0.000000,5.810628,0.774275,1.899833,10.895982,0.0
75%,12.280328,12.349596,12.230850,12.290223,12.329805,3.148443e+07,3.724712e+08,2.0,0.112029,1.0,0.631583,6.721107,0.940932,2.161991,12.496256,0.0
max,13.507371,13.853714,13.220401,13.507371,13.507371,3.796536e+08,5.099364e+09,2.0,1.350900,1.0,5.193799,7.386724,1.034116,2.376102,31.326051,0.0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 18 columns):
date           245 non-null object
code           245 non-null object
open           245 non-null float64
high           245 non-null float64
low            245 non-null float64
close          245 non-null float64
preclose       245 non-null float64
volume         245 non-null int64
amount         245 non-null float64
adjustflag     245 non-null int64
turn           245 non-null float64
tradestatus    245 non-null int64
pctChg         245 non-null float64
peTTM          245 non-null float64
pbMRQ          245 non-null float64
psTTM          245 non-null float64
pcfNcfTTM      245 non-null float64
isST           245 non-null int64
dtypes: float64(12), int64(4), object(2)
memory usage: 34.5+ KB

In [8]:
print(data.index)
print(data.index.name)
print(data.columns)
print(data.values)

RangeIndex(start=0, stop=245, step=1)
None
Index(['date', 'code', 'open', 'high', 'low', 'close', 'preclose', 'volume',
       'amount', 'adjustflag', 'turn', 'tradestatus', 'pctChg', 'peTTM',
       'pbMRQ', 'psTTM', 'pcfNcfTTM', 'isST'],
      dtype='object')
[['2017-12-07' 'sh.600000' 12.81468545 ... 2.3106259999999996 -2.043354 0]
 ['2017-12-08' 'sh.600000' 12.84437198 ... 2.3052770000000002 -2.038624 0]
 ['2017-12-11' 'sh.600000' 12.78499892 ... 2.312409 -2.04493 0]
 ...
 ['2018-12-05' 'sh.600000' 10.99 ... 1.8963849999999998 3.107385 0]
 ['2018-12-06' 'sh.600000' 10.82 ... 1.879146 3.079136 0]
 ['2018-12-07' 'sh.600000' 10.94 ... 1.8774220000000001
  3.0763119999999997 0]]

In [10]:
data[:3]

,date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM,isST
0,2017-12-07,sh.600000,12.814685,12.893850,12.775103,12.824581,12.824581,34802229,451233524.0,2,0.123835,1,0.000000,7.004418,0.981842,2.310626,-2.043354,0
1,2017-12-08,sh.600000,12.844372,12.854267,12.735521,12.794894,12.824581,31296221,404411517.0,2,0.111360,1,-0.231479,6.988205,0.979569,2.305277,-2.038624,0
2,2017-12-11,sh.600000,12.784999,12.903745,12.715730,12.834476,12.794894,36649902,474566888.0,2,0.130409,1,0.309358,7.009823,0.982600,2.312409,-2.044930,0

In [16]:
type(data[['date']])

pandas.core.frame.DataFrame

In [17]:
type(data[['date','open','close']])

pandas.core.frame.DataFrame

In [18]:
data[data.close > 11.08]

,date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM,isST
0,2017-12-07,sh.600000,12.814685,12.893850,12.775103,12.824581,12.824581,34802229,4.512335e+08,2,0.123835,1,0.000000,7.004418,0.981842,2.310626,-2.043354,0
1,2017-12-08,sh.600000,12.844372,12.854267,12.735521,12.794894,12.824581,31296221,4.044115e+08,2,0.111360,1,-0.231479,6.988205,0.979569,2.305277,-2.038624,0
2,2017-12-11,sh.600000,12.784999,12.903745,12.715730,12.834476,12.794894,36649902,4.745669e+08,2,0.130409,1,0.309358,7.009823,0.982600,2.312409,-2.044930,0
3,2017-12-12,sh.600000,12.834476,12.834476,12.606880,12.616775,12.834476,30370097,3.901131e+08,2,0.108064,1,-1.696224,6.890921,0.965933,2.273185,-2.010244,0
4,2017-12-13,sh.600000,12.666253,12.676148,12.498029,12.606880,12.616775,19345338,2.463311e+08,2,0.068835,1,-0.078433,6.885516,0.965175,2.271402,-2.008667,0
5,2017-12-14,sh.600000,12.656357,12.656357,12.527716,12.557402,12.606880,16141678,2.052195e+08,2,0.057436,1,-0.392466,6.858493,0.961387,2.262488,-2.000784,0
6,2017-12-15,sh.600000,12.557402,12.596984,12.478238,12.488134,12.557402,16210108,2.053238e+08,2,0.057679,1,-0.551613,6.820661,0.956084,2.250008,-1.989747,0
7,2017-12-18,sh.600000,12.577193,12.577193,12.478238,12.517820,12.488134,13445648,1.701400e+08,2,0.047843,1,0.237716,6.836874,0.958357,2.255356,-1.994477,0
8,2017-12-19,sh.600000,12.517820,12.626671,12.488134,12.616775,12.517820,18399603,2.338847e+08,2,0.065470,1,0.790517,6.890921,0.965933,2.273185,-2.010244,0
9,2017-12-20,sh.600000,12.626671,12.626671,12.468343,12.596984,12.616775,26639844,3.376035e+08,2,0.094791,1,-0.156866,6.880112,0.964417,2.269619,-2.007090,0
10,2017-12-21,sh.600000,12.537611,12.646462,12.468343,12.567298,12.596984,21052388,2.676242e+08,2,0.074909,1,-0.235662,6.863898,0.962145,2.264271,-2.002360,0
11,2017-12-22,sh.600000,12.547507,12.587089,12.478238,12.488134,12.567298,16076938,2.034688e+08,2,0.057206,1,-0.629921,6.820661,0.956084,2.250008,-1.989747,0
12,2017-12-25,sh.600000,12.478238,12.547507,12.428761,12.458447,12.488134,19306662,2.435537e+08,2,0.068698,1,-0.237716,6.804447,0.953811,2.244659,-1.985017,0
13,2017-12-26,sh.600000,12.438656,12.527716,12.428761,12.507925,12.458447,15225722,1.922191e+08,2,0.054177,1,0.397142,6.831470,0.957599,2.253573,-1.992900,0
14,2017-12-27,sh.600000,12.517820,12.527716,12.399074,12.488134,12.507925,32731881,4.121980e+08,2,0.116468,1,-0.158231,6.820661,0.956084,2.250008,-1.989747,0
15,2017-12-28,sh.600000,12.468343,12.527716,12.399074,12.408970,12.488134,23870824,3.008340e+08,2,0.084938,1,-0.633914,6.777423,0.950023,2.235744,-1.977134,0
16,2017-12-29,sh.600000,12.389179,12.488134,12.379283,12.458447,12.408970,16351826,2.057529e+08,2,0.058184,1,0.398726,6.804447,0.953811,2.244659,-1.985017,0
17,2018-01-02,sh.600000,12.478238,12.636566,12.468343,12.587089,12.458447,31323053,3.986150e+08,2,0.111455,1,1.032566,6.874707,0.963660,2.267837,-2.005514,0
18,2018-01-03,sh.600000,12.596984,12.666253,12.527716,12.527716,12.587089,37839101,4.809548e+08,2,0.134641,1,-0.471701,6.842279,0.959114,2.257139,-1.996054,0
19,2018-01-04,sh.600000,12.567298,12.596984,12.488134,12.527716,12.527716,27883804,3.532058e+08,2,0.099217,1,0.000000,6.842279,0.959114,2.257139,-1.996054,0
20,2018-01-05,sh.600000,12.537611,12.577193,12.488134,12.557402,12.527716,31026744,3.930582e+08,2,0.110401,1,0.236965,6.858493,0.961387,2.262488,-2.000784,0
21,2018-01-08,sh.600000,12.557402,12.577193,12.498029,12.547507,12.557402,31389887,3.978422e+08,2,0.111693,1,-0.078797,6.861806,0.960630,2.207251,-1.999207,0
22,2018-01-09,sh.600000,12.547507,12.606880,12.527716,12.567298,12.547507,26215432,3.328483e+08,2,0.093281,1,0.157725,6.872629,0.962145,2.210732,-2.002360,0
23,2018-01-10,sh.600000,12.567298,12.953223,12.547507,12.883954,12.567298,90679990,1.174202e+09,2,0.322661,1,2.519690,7.045798,0.986388,2.266435,-2.052814,0
24,2018-01-11,sh.600000,12.814685,12.903745,12.735521,12.804790,12.883954,37816412,4.895889e+08,2,0.134560,1,-0.614446,7.002506,0.980327,2.252510,-2.040200,0
25,2018-01-12,sh.600000,12.834476,12.864163,12.765208,12.775103,12.804790,24203419,3.132151e+08,2,0.086122,1,-0.231837,6.986271,0.978054,2.247287,-2.035470,0
26,2018-01-15,sh.600000,12.745417,12.943327,12.715730,12.883954,12.775103,61320680,7.968611e+08,2,0.218194,1,0.852058,7.045798,0.986388,2.266435,-2.052814,0
27,2018-01-16,sh.600000,12.834476,12.923536,12.646462,12.765208,12.883954,74892652,9.637011e+08,2,0.266486,1,-0.921665,6.980860,0.977297,2.245547,-2.033894,0
28,2018-01-17,sh.600000,12.775103,13.279774,12.755312,12.963118,12.765208,127132813,1.675235e+09,2,0.452369,1,1.550394,7.089090,0.992448,2.280361,-2.065427,0
29,2018-01-18,sh.600000,13.002700,13.111551,12.913641,13.101655,12.963118,111608076,1.465159e+09,2,0.397129,1,1.068698,7.164851,1.003055,2.304732,-2.087500,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,2018-03-19,sh.600000,12.181373,12.201164,12.131895,12.181373,12.171477,16896048,2.078193e+08,2,0.060120,1,0.081303,6.661580,0.932599,2.142843,-1.940871,0
67,2018-03-20,sh.600000,12.151686,12.260537,12.122000,12.191268,12.181373,20672283,2.541878e+08,2,0.073557,1,0.081229,6.666992,0.933356,2.144584,-1.942447,0
68,2018-03-21,sh.600000,12.211059,12.270432,12.151686,12.161582,12.191268,23878465,2.948722e+08,2,0.084965,1,-0.243504,6.650757,0.931083,2.139362,-1.937717,0
69,2018-03-22,sh.600000,12.220955,12.220955,12.122000,12.122000,12.161582,22948484,2.819750e+08,2,0.081656,1,-0.325468,6.629111,0.928053,2.132399,-1.931411,0
70,2018-03-23,sh.600000,11.874612,11.933985,11.518374,11.587642,12.122000,57106391,6.766797e+08,2,0.203198,1,-4.408163,6.336889,0.887143,2.038399,-1.846271,0
71,2018-03-26,sh.600000,11.587642,11.627224,11.379836,11.488687,11.587642,36425054,4.222335e+08,2,0.129609,1,-0.853974,6.282774,0.879567,2.020992,-1.830504,0
72,2018-03-27,sh.600000,11.577747,11.647015,11.439210,11.498583,11.488687,27332809,3.185867e+08,2,0.097257,1,0.086135,6.288185,0.880325,2.022733,-1.832081,0
73,2018-03-28,sh.600000,11.409523,11.627224,11.399628,11.449105,11.498583,22911282,2.661215e+08,2,0.081524,1,-0.430294,6.261128,0.876537,2.014029,-1.824198,0
74,2018-03-29,sh.600000,11.449105,11.587642,11.330359,11.498583,11.449105,33108805,3.830650e+08,2,0.117809,1,0.432154,6.288185,0.880325,2.022733,-1.832081,0
75,2018-03-30,sh.600000,11.508478,11.567851,11.488687,11.528269,11.498583,23271965,2.709877e+08,2,0.082807,1,0.258173,6.304420,0.882597,2.027955,-1.836811,0
76,2018-04-02,sh.600000,11.557956,11.696493,11.528269,11.587642,11.528269,27719599,3.256676e+08,2,0.098633,1,0.515025,6.336889,0.887143,2.038399,-1.846271,0
77,2018-04-03,sh.600000,11.538165,11.548060,11.419419,11.439210,11.587642,18303514,2.119069e+08,2,0.065128,1,-1.280953,6.255716,0.875779,2.012288,-1.822621,0
78,2018-04-04,sh.600000,11.488687,11.528269,11.409523,11.409523,11.439210,19637509,2.276897e+08,2,0.069875,1,-0.259522,6.239482,0.873506,2.007066,-1.817891,0
79,2018-04-09,sh.600000,11.409523,11.468896,11.369941,11.379836,11.409523,16722481,1.927095e+08,2,0.059503,1,-0.260188,6.223247,0.871233,2.001844,-1.813161,0
80,2018-04-10,sh.600000,11.399628,11.666806,11.389732,11.647015,11.379836,28748298,3.360768e+08,2,0.102293,1,2.347830,6.369358,0.891688,2.048844,-1.855731,0
81,2018-04-11,sh.600000,11.666806,11.894403,11.627224,11.785552,11.647015,31298519,3.724712e+08,2,0.111368,1,1.189459,6.445119,0.902295,2.073214,-1.877804,0
82,2018-04-12,sh.600000,11.785552,11.835030,11.637120,11.656911,11.785552,18824289,2.227695e+08,2,0.066981,1,-1.091521,6.374770,0.892446,2.050584,-1.857307,0
83,2018-04-13,sh.600000,11.706388,11.765761,11.567851,11.567851,11.656911,14094853,1.660155e+08,2,0.050153,1,-0.764008,6.326066,0.885628,2.034918,-1.843118,0
84,2018-04-16,sh.600000,11.676702,11.676702,11.419419,11.429314,11.567851,23720095,2.750707e+08,2,0.084402,1,-1.197600,6.250305,0.875021,2.010548,-1.821044,0
85,2018-04-17,sh.600000,11.439210,11.577747,11.429314,11.429314,11.429314,25469983,2.962340e+08,2,0.090628,1,0.000000,6.250305,0.875021,2.010548,-1.821044,0
86,2018-04-18,sh.600000,11.627224,11.666806,11.538165,11.607433,11.429314,26295275,3.084855e+08,2,0.093565,1,1.558436,6.347712,0.888658,2.041881,-1.849424,0
87,2018-04-19,sh.600000,11.676702,11.765761,11.637120,11.676702,11.607433,16553270,1.957712e+08,2,0.058901,1,0.596766,6.385593,0.893961,2.054066,-1.860461,0
88,2018-04-20,sh.600000,11.617329,11.666806,11.449105,11.488687,11.676702,18377407,2.139652e+08,2,0.065391,1,-1.610174,6.282774,0.879567,2.020992,-1.830504,0
89,2018-04-23,sh.600000,11.439210,11.627224,11.409523,11.478792,11.488687,18181610,2.110465e+08,2,0.064695,1,-0.086126,6.277362,0.878809,2.019251,-1.828928,0
90,2018-04-24,sh.600000,11.439210,11.656911,11.439210,11.656911,11.478792,23032861,2.698718e+08,2,0.081956,1,1.551718,6.374770,0.892446,2.050584,-1.857307,0
91,2018-04-25,sh.600000,11.587642,11.647015,11.528269,11.538165,11.656911,16082634,1.881492e+08,2,0.057226,1,-1.018675,6.309831,0.883355,2.029696,-1.838388,0
92,2018-04-26,sh.600000,11.607433,11.656911,11.429314,11.449105,11.538165,18205794,2.119875e+08,2,0.064781,1,-0.771871,6.261128,0.876537,2.014029,-1.824198,0
93,2018-04-27,sh.600000,11.459001,11.548060,11.429314,11.488687,11.449105,23450783,2.723286e+08,2,0.083444,1,0.345721,6.282774,0.879567,2.020992,-1.830504,0
219,2018-11-02,sh.600000,11.100000,11.250000,10.940000,11.180000,10.890000,47788920,5.309137e+08,2,0.170045,1,2.662993,5.904959,0.771319,1.927417,3.158234,0
220,2018-11-05,sh.600000,11.150000,11.250000,11.080000,11.140000,11.180000,17012759,1.894812e+08,2,0.060536,1,-0.357781,5.883832,0.768560,1.920521,3.146934,0

In [19]:
df1 = data.set_index('date')
df1

,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM,isST
date,,,,,,,,,,,,,,,,,
2017-12-07,sh.600000,12.814685,12.893850,12.775103,12.824581,12.824581,34802229,4.512335e+08,2,0.123835,1,0.000000,7.004418,0.981842,2.310626,-2.043354,0
2017-12-08,sh.600000,12.844372,12.854267,12.735521,12.794894,12.824581,31296221,4.044115e+08,2,0.111360,1,-0.231479,6.988205,0.979569,2.305277,-2.038624,0
2017-12-11,sh.600000,12.784999,12.903745,12.715730,12.834476,12.794894,36649902,4.745669e+08,2,0.130409,1,0.309358,7.009823,0.982600,2.312409,-2.044930,0
2017-12-12,sh.600000,12.834476,12.834476,12.606880,12.616775,12.834476,30370097,3.901131e+08,2,0.108064,1,-1.696224,6.890921,0.965933,2.273185,-2.010244,0
2017-12-13,sh.600000,12.666253,12.676148,12.498029,12.606880,12.616775,19345338,2.463311e+08,2,0.068835,1,-0.078433,6.885516,0.965175,2.271402,-2.008667,0
2017-12-14,sh.600000,12.656357,12.656357,12.527716,12.557402,12.606880,16141678,2.052195e+08,2,0.057436,1,-0.392466,6.858493,0.961387,2.262488,-2.000784,0
2017-12-15,sh.600000,12.557402,12.596984,12.478238,12.488134,12.557402,16210108,2.053238e+08,2,0.057679,1,-0.551613,6.820661,0.956084,2.250008,-1.989747,0
2017-12-18,sh.600000,12.577193,12.577193,12.478238,12.517820,12.488134,13445648,1.701400e+08,2,0.047843,1,0.237716,6.836874,0.958357,2.255356,-1.994477,0
2017-12-19,sh.600000,12.517820,12.626671,12.488134,12.616775,12.517820,18399603,2.338847e+08,2,0.065470,1,0.790517,6.890921,0.965933,2.273185,-2.010244,0
2017-12-20,sh.600000,12.626671,12.626671,12.468343,12.596984,12.616775,26639844,3.376035e+08,2,0.094791,1,-0.156866,6.880112,0.964417,2.269619,-2.007090,0
2017-12-21,sh.600000,12.537611,12.646462,12.468343,12.567298,12.596984,21052388,2.676242e+08,2,0.074909,1,-0.235662,6.863898,0.962145,2.264271,-2.002360,0
2017-12-22,sh.600000,12.547507,12.587089,12.478238,12.488134,12.567298,16076938,2.034688e+08,2,0.057206,1,-0.629921,6.820661,0.956084,2.250008,-1.989747,0
2017-12-25,sh.600000,12.478238,12.547507,12.428761,12.458447,12.488134,19306662,2.435537e+08,2,0.068698,1,-0.237716,6.804447,0.953811,2.244659,-1.985017,0
2017-12-26,sh.600000,12.438656,12.527716,12.428761,12.507925,12.458447,15225722,1.922191e+08,2,0.054177,1,0.397142,6.831470,0.957599,2.253573,-1.992900,0
2017-12-27,sh.600000,12.517820,12.527716,12.399074,12.488134,12.507925,32731881,4.121980e+08,2,0.116468,1,-0.158231,6.820661,0.956084,2.250008,-1.989747,0
2017-12-28,sh.600000,12.468343,12.527716,12.399074,12.408970,12.488134,23870824,3.008340e+08,2,0.084938,1,-0.633914,6.777423,0.950023,2.235744,-1.977134,0
2017-12-29,sh.600000,12.389179,12.488134,12.379283,12.458447,12.408970,16351826,2.057529e+08,2,0.058184,1,0.398726,6.804447,0.953811,2.244659,-1.985017,0
2018-01-02,sh.600000,12.478238,12.636566,12.468343,12.587089,12.458447,31323053,3.986150e+08,2,0.111455,1,1.032566,6.874707,0.963660,2.267837,-2.005514,0
2018-01-03,sh.600000,12.596984,12.666253,12.527716,12.527716,12.587089,37839101,4.809548e+08,2,0.134641,1,-0.471701,6.842279,0.959114,2.257139,-1.996054,0
2018-01-04,sh.600000,12.567298,12.596984,12.488134,12.527716,12.527716,27883804,3.532058e+08,2,0.099217,1,0.000000,6.842279,0.959114,2.257139,-1.996054,0
2018-01-05,sh.600000,12.537611,12.577193,12.488134,12.557402,12.527716,31026744,3.930582e+08,2,0.110401,1,0.236965,6.858493,0.961387,2.262488,-2.000784,0
2018-01-08,sh.600000,12.557402,12.577193,12.498029,12.547507,12.557402,31389887,3.978422e+08,2,0.111693,1,-0.078797,6.861806,0.960630,2.207251,-1.999207,0
2018-01-09,sh.600000,12.547507,12.606880,12.527716,12.567298,12.547507,26215432,3.328483e+08,2,0.093281,1,0.157725,6.872629,0.962145,2.210732,-2.002360,0
2018-01-10,sh.600000,12.567298,12.953223,12.547507,12.883954,12.567298,90679990,1.174202e+09,2,0.322661,1,2.519690,7.045798,0.986388,2.266435,-2.052814,0
2018-01-11,sh.600000,12.814685,12.903745,12.735521,12.804790,12.883954,37816412,4.895889e+08,2,0.134560,1,-0.614446,7.002506,0.980327,2.252510,-2.040200,0
2018-01-12,sh.600000,12.834476,12.864163,12.765208,12.775103,12.804790,24203419,3.132151e+08,2,0.086122,1,-0.231837,6.986271,0.978054,2.247287,-2.035470,0
2018-01-15,sh.600000,12.745417,12.943327,12.715730,12.883954,12.775103,61320680,7.968611e+08,2,0.218194,1,0.852058,7.045798,0.986388,2.266435,-2.052814,0
2018-01-16,sh.600000,12.834476,12.923536,12.646462,12.765208,12.883954,74892652,9.637011e+08,2,0.266486,1,-0.921665,6.980860,0.977297,2.245547,-2.033894,0
2018-01-17,sh.600000,12.775103,13.279774,12.755312,12.963118,12.765208,127132813,1.675235e+09,2,0.452369,1,1.550394,7.089090,0.992448,2.280361,-2.065427,0
2018-01-18,sh.600000,13.002700,13.111551,12.913641,13.101655,12.963118,111608076,1.465159e+09,2,0.397129,1,1.068698,7.164851,1.003055,2.304732,-2.087500,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-10-29,sh.600000,11.080000,11.120000,10.710000,10.790000,10.920000,35265959,3.851165e+08,2,0.125485,1,-1.190477,5.793951,0.770703,1.898393,30.868318,0
2018-10-30,sh.600000,10.930000,11.050000,10.890000,10.950000,10.790000,33086049,3.630181e+08,2,0.117728,1,1.482853,5.879867,0.782132,1.926544,31.326051,0
2018-10-31,sh.600000,10.990000,11.030000,10.870000,10.980000,10.950000,21737114,2.375830e+08,2,0.077346,1,0.273970,5.799324,0.757521,1.892937,3.101736,0
2018-11-01,sh.600000,11.050000,11.090000,10.860000,10.890000,10.980000,23505322,2.577817e+08,2,0.083638,1,-0.819665,5.751789,0.751312,1.877422,3.076312,0
2018-11-02,sh.600000,11.100000,11.250000,10.940000,11.180000,10.890000,47788920,5.309137e+08,2,0.170045,1,2.662993,5.904959,0.771319,1.927417,3.158234,0
2018-11-05,sh.600000,11.150000,11.250000,11.080000,11.140000,11.180000,17012759,1.894812e+08,2,0.060536,1,-0.357781,5.883832,0.768560,1.920521,3.146934,0
2018-11-06,sh.600000,11.130000,11.150000,11.000000,11.030000,11.140000,18422477,2.035658e+08,2,0.065552,1,-0.987438,5.825733,0.760971,1.901557,3.115860,0
2018-11-07,sh.600000,11.090000,11.100000,10.870000,10.900000,11.030000,20843864,2.288365e+08,2,0.074168,1,-1.178605,5.757070,0.752002,1.879146,3.079136,0
2018-11-08,sh.600000,11.050000,11.100000,10.900000,11.060000,10.900000,19991683,2.205061e+08,2,0.071135,1,1.467897,5.841578,0.763040,1.906729,3.124335,0
2018-11-09,sh.600000,10.990000,11.030000,10.700000,10.750000,11.060000,25570050,2.770049e+08,2,0.090984,1,-2.802897,5.677845,0.741653,1.853286,3.036763,0
2018-11-12,sh.600000,10.770000,10.950000,10.750000,10.800000,10.750000,27015827,2.924782e+08,2,0.096129,1,0.465118,5.704253,0.745103,1.861906,3.050888,0
2018-11-13,sh.600000,10.680000,10.900000,10.680000,10.820000,10.800000,20708729,2.235415e+08,2,0.073687,1,0.185181,5.714817,0.746483,1.865354,3.056537,0
2018-11-14,sh.600000,10.870000,10.870000,10.680000,10.700000,10.820000,17998183,1.938097e+08,2,0.064042,1,-1.109056,5.651436,0.738204,1.844666,3.022639,0
2018-11-15,sh.600000,10.720000,10.810000,10.650000,10.770000,10.700000,16580059,1.781446e+08,2,0.058996,1,0.654212,5.688408,0.743033,1.856734,3.042413,0
2018-11-16,sh.600000,10.770000,10.850000,10.710000,10.760000,10.770000,21394417,2.305096e+08,2,0.076127,1,-0.092853,5.683126,0.742343,1.855010,3.039588,0
2018-11-19,sh.600000,10.860000,10.900000,10.770000,10.880000,10.760000,21384793,2.319997e+08,2,0.076092,1,1.115241,5.746507,0.750622,1.875698,3.073487,0
2018-11-20,sh.600000,10.870000,10.890000,10.650000,10.690000,10.880000,21883780,2.349592e+08,2,0.077868,1,-1.746328,5.646154,0.737514,1.842942,3.019814,0
2018-11-21,sh.600000,10.610000,10.720000,10.610000,10.660000,10.690000,16027458,1.709157e+08,2,0.057030,1,-0.280634,5.630309,0.735444,1.837770,3.011339,0
2018-11-22,sh.600000,10.730000,10.730000,10.570000,10.640000,10.660000,14008305,1.487451e+08,2,0.049845,1,-0.187613,5.619746,0.734064,1.834322,3.005689,0
2018-11-23,sh.600000,10.600000,10.660000,10.500000,10.500000,10.640000,14715010,1.555661e+08,2,0.052360,1,-1.315793,5.545802,0.724405,1.810186,2.966141,0
2018-11-26,sh.600000,10.660000,10.660000,10.430000,10.500000,10.500000,14377396,1.516094e+08,2,0.051158,1,0.000000,5.545802,0.724405,1.810186,2.966141,0
2018-11-27,sh.600000,10.500000,10.610000,10.450000,10.490000,10.500000,15084666,1.588533e+08,2,0.053675,1,-0.095240,5.540520,0.723716,1.808462,2.963316,0
2018-11-28,sh.600000,10.560000,10.620000,10.500000,10.580000,10.490000,18339621,1.939149e+08,2,0.065257,1,0.857962,5.588056,0.729925,1.823978,2.988740,0
2018-11-29,sh.600000,10.640000,10.750000,10.540000,10.630000,10.580000,20685685,2.206701e+08,2,0.073605,1,0.472592,5.614464,0.733374,1.832598,3.002864,0
2018-11-30,sh.600000,10.650000,10.750000,10.620000,10.710000,10.630000,28572651,3.054687e+08,2,0.101668,1,0.752586,5.656718,0.738894,1.846390,3.025463,0
2018-12-03,sh.600000,10.990000,11.050000,10.840000,11.020000,10.710000,43049070,4.724384e+08,2,0.153179,1,2.894495,5.820451,0.760281,1.899833,3.113035,0
2018-12-04,sh.600000,11.000000,11.080000,10.970000,11.080000,11.020000,20811293,2.297137e+08,2,0.074052,1,0.544460,5.852141,0.764420,1.910177,3.129985,0
2018-12-05,sh.600000,10.990000,11.100000,10.960000,11.000000,11.080000,25491217,2.811896e+08,2,0.090704,1,-0.722021,5.809888,0.758901,1.896385,3.107385,0
2018-12-06,sh.600000,10.820000,10.930000,10.820000,10.900000,11.000000,23597997,2.565331e+08,2,0.083967,1,-0.909094,5.757070,0.752002,1.879146,3.079136,0
2018-12-07,sh.600000,10.940000,11.030000,10.880000,10.890000,10.900000,10580550,1.157603e+08,2,0.037648,1,-0.091736,5.751789,0.751312,1.877422,3.076312,0

In [20]:
df1.loc['2017-12-11':'2017-12-20']

,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM,isST
date,,,,,,,,,,,,,,,,,
2017-12-11,sh.600000,12.784999,12.903745,12.715730,12.834476,12.794894,36649902,474566888.0,2,0.130409,1,0.309358,7.009823,0.982600,2.312409,-2.044930,0
2017-12-12,sh.600000,12.834476,12.834476,12.606880,12.616775,12.834476,30370097,390113096.0,2,0.108064,1,-1.696224,6.890921,0.965933,2.273185,-2.010244,0
2017-12-13,sh.600000,12.666253,12.676148,12.498029,12.606880,12.616775,19345338,246331123.0,2,0.068835,1,-0.078433,6.885516,0.965175,2.271402,-2.008667,0
2017-12-14,sh.600000,12.656357,12.656357,12.527716,12.557402,12.606880,16141678,205219487.0,2,0.057436,1,-0.392466,6.858493,0.961387,2.262488,-2.000784,0
2017-12-15,sh.600000,12.557402,12.596984,12.478238,12.488134,12.557402,16210108,205323767.0,2,0.057679,1,-0.551613,6.820661,0.956084,2.250008,-1.989747,0
2017-12-18,sh.600000,12.577193,12.577193,12.478238,12.517820,12.488134,13445648,170140035.0,2,0.047843,1,0.237716,6.836874,0.958357,2.255356,-1.994477,0
2017-12-19,sh.600000,12.517820,12.626671,12.488134,12.616775,12.517820,18399603,233884666.0,2,0.065470,1,0.790517,6.890921,0.965933,2.273185,-2.010244,0
2017-12-20,sh.600000,12.626671,12.626671,12.468343,12.596984,12.616775,26639844,337603451.0,2,0.094791,1,-0.156866,6.880112,0.964417,2.269619,-2.007090,0

In [22]:
df1.loc[:,'open':'close']

                 open       high        low      close
date
2017-12-07  12.814685  12.893850  12.775103  12.824581
2017-12-08  12.844372  12.854267  12.735521  12.794894
2017-12-11  12.784999  12.903745  12.715730  12.834476
2017-12-12  12.834476  12.834476  12.606880  12.616775
2017-12-13  12.666253  12.676148  12.498029  12.606880
2017-12-14  12.656357  12.656357  12.527716  12.557402
2017-12-15  12.557402  12.596984  12.478238  12.488134
2017-12-18  12.577193  12.577193  12.478238  12.517820
2017-12-19  12.517820  12.626671  12.488134  12.616775
2017-12-20  12.626671  12.626671  12.468343  12.596984
2017-12-21  12.537611  12.646462  12.468343  12.567298
2017-12-22  12.547507  12.587089  12.478238  12.488134
2017-12-25  12.478238  12.547507  12.428761  12.458447
2017-12-26  12.438656  12.527716  12.428761  12.507925
2017-12-27  12.517820  12.527716  12.399074  12.488134
2017-12-28  12.468343  12.527716  12.399074  12.408970
2017-12-29  12.389179  12.488134  12.379283  12.458447
2018-01-02  12.478238  12.636566  12.468343  12.587089
2018-01-03  12.596984  12.666253  12.527716  12.527716
2018-01-04  12.567298  12.596984  12.488134  12.527716
2018-01-05  12.537611  12.577193  12.488134  12.557402
2018-01-08  12.557402  12.577193  12.498029  12.547507
2018-01-09  12.547507  12.606880  12.527716  12.567298
2018-01-10  12.567298  12.953223  12.547507  12.883954
2018-01-11  12.814685  12.903745  12.735521  12.804790
2018-01-12  12.834476  12.864163  12.765208  12.775103
2018-01-15  12.745417  12.943327  12.715730  12.883954
2018-01-16  12.834476  12.923536  12.646462  12.765208
2018-01-17  12.775103  13.279774  12.755312  12.963118
2018-01-18  13.002700  13.111551  12.913641  13.101655
...               ...        ...        ...        ...
2018-10-29  11.080000  11.120000  10.710000  10.790000
2018-10-30  10.930000  11.050000  10.890000  10.950000
2018-10-31  10.990000  11.030000  10.870000  10.980000
2018-11-01  11.050000  11.090000  10.860000  10.890000
2018-11-02  11.100000  11.250000  10.940000  11.180000
2018-11-05  11.150000  11.250000  11.080000  11.140000
2018-11-06  11.130000  11.150000  11.000000  11.030000
2018-11-07  11.090000  11.100000  10.870000  10.900000
2018-11-08  11.050000  11.100000  10.900000  11.060000
2018-11-09  10.990000  11.030000  10.700000  10.750000
2018-11-12  10.770000  10.950000  10.750000  10.800000
2018-11-13  10.680000  10.900000  10.680000  10.820000
2018-11-14  10.870000  10.870000  10.680000  10.700000
2018-11-15  10.720000  10.810000  10.650000  10.770000
2018-11-16  10.770000  10.850000  10.710000  10.760000
2018-11-19  10.860000  10.900000  10.770000  10.880000
2018-11-20  10.870000  10.890000  10.650000  10.690000
2018-11-21  10.610000  10.720000  10.610000  10.660000
2018-11-22  10.730000  10.730000  10.570000  10.640000
2018-11-23  10.600000  10.660000  10.500000  10.500000
2018-11-26  10.660000  10.660000  10.430000  10.500000
2018-11-27  10.500000  10.610000  10.450000  10.490000
2018-11-28  10.560000  10.620000  10.500000  10.580000
2018-11-29  10.640000  10.750000  10.540000  10.630000
2018-11-30  10.650000  10.750000  10.620000  10.710000
2018-12-03  10.990000  11.050000  10.840000  11.020000
2018-12-04  11.000000  11.080000  10.970000  11.080000
2018-12-05  10.990000  11.100000  10.960000  11.000000
2018-12-06  10.820000  10.930000  10.820000  10.900000
2018-12-07  10.940000  11.030000  10.880000  10.890000

[245 rows x 4 columns]

In [23]:
df1.loc['2018-07-01':'2018-07-08','open':'close']

                open      high       low     close
date
2018-07-02  9.450212  9.450212  9.133556  9.192929
2018-07-03  9.192929  9.281988  9.103869  9.252302
2018-07-04  9.242406  9.321570  9.183033  9.212720
2018-07-05  9.163242  9.252302  9.123660  9.163242
2018-07-06  9.212720  9.331466  9.074183  9.272093